### ISSUE TITLE
Errno::ENOENT at /man No such file or directory

### ISSUE THREAD

**Issue by Neener54** [jimeh/manservant#4]
I keep getting this error after installing.  I am not using pow.
After getting this error I installed man2html from source in hopes that the command it was calling was breaking because it couldn't find the file.  No dice.

Errno::ENOENT at /man
No such file or directory - command -v man2html
file: man_page.rb location: ` line: 64

**Comment by jimeh** [comment]
This should now be fixed as of 4b66bb75f308c8f67c127e6661e3c184f25ee78f.
